### ISSUE TITLE
Downloading TCGA data

### ISSUE THREAD

**Issue by MarioPaps** [isyangshu/MambaMIL#10]
I have a question on downloading TCGA data. I used the gdc command line tool to download the WSIs for BRCA. However, a significant number of svs files did not download correctly, resulting in a lot of files with a 'svs.partial' file extension. 

Is there a way to avoid this issue so that I can use the max number of WSIs?

**Comment by wyhsleep** [comment]
You might want to check your network connection.

**Comment by MarioPaps** [comment]
I was able to download BLCA without issues though. Did you donwload them with gdc client from the terminal or did you use another method?

**Comment by isyangshu** [comment]
We use the gdc client from the terminal.

**Comment by MarioPaps** [comment]
Did you download all the files at once? I tried both at once and in stages and some files persist not to download. For example:
![image](https://github.com/isyangshu/MambaMIL/assets/20114246/a59324d5-9f12-43b2-be82-dae99672a761)
