### ISSUE TITLE
May I obtain one .pt file of one image from BRACS

### ISSUE THREAD

**Issue by poult-lab** [isyangshu/MambaMIL#12]
Congratulations on your early acceptance by MICCAI!

I understand that the images were processed at 512x512 (20x), with a batch size of 1. If I am correct, each image was partitioned into 20 patches, each sized 512x512. Could I please obtain a .pt file for one image? I would like to feed this .pt file into the model to examine how each part of the model works.

Thank you!

**Comment by isyangshu** [comment]
Firstly, the 20x means the scale version of the whole-slide images.
Thus, each image can be partitioned into many patches (not 20 and it's different between different images), and each patch is 512*512.

I can't upload the .pt file for one WSI, and I will send you an email.

**Comment by poult-lab** [comment]
> Firstly, the 20x means the scale version of the whole-slide images. Thus, each image can be partitioned into many patches (not 20 and it's different between different images), and each patch is 512*512.
> 
> I can't upload the .pt file for one WSI, and I will send you an email.

Thanks a lot, bro. I already got the .pt file. Actually, I still have one question about the architecture of MambaMIL. I noticed the architecture is quite unique and I’m curious about where you got the inspiration for it.
