### ISSUE TITLE
Order of patch sequence in Mamba

### ISSUE THREAD

**Issue by anhtienng** [isyangshu/MambaMIL#14]
Thank you for your work.

What is the order of patch sequences used in the Table 3 ?

<img width="900" alt="image" src="https://github.com/isyangshu/MambaMIL/assets/47650134/975982bb-50b1-491b-aa17-1389cb74c6ea">

I mean how the patch feature sequences were organized when being feed into the Mamba blocks ?

Thank you.

**Comment by anhtienng** [comment]
<img width="738" alt="image" src="https://github.com/isyangshu/MambaMIL/assets/47650134/8cdf278c-cdc6-45d7-ab87-5964c0dc0fd9">

To be specific, what is the order of features after the Feature Extractor ? Is it lawnmower ?

**Comment by wyhsleep** [comment]
Sorry for the late reply. We actually follow the row-major order. This means we process each row from left to right, one row after another.
