### ISSUE TITLE
Regarding the package import

### ISSUE THREAD

**Issue by ZhengtingJiang** [isyangshu/MambaMIL#15]
Hi! I am encountering a problem and I cannot solve it.
![屏幕截图 2024-06-12 105719](https://github.com/isyangshu/MambaMIL/assets/71182080/1ebc3ffb-22f4-48e2-b171-4c8445f7724e)

Could you pls give some advice?

**Comment by wyhsleep** [comment]
What is your CUDA version?

**Comment by ZhengtingJiang** [comment]
Hi! It is 
Ubuntu Server 22.04 LTS R535 **CUDA 12.2**

**Comment by wyhsleep** [comment]
Maybe you can try CUDA11.8. The code works fine in that version and we will release a version that supports CUDA12.X in the near future. If you have further problems, feel free to contact us.

**Comment by ZhengtingJiang** [comment]
Thank you! I would have a try.
