### ISSUE TITLE
Aggregate results of Mamba

### ISSUE THREAD

**Issue by anhtienng** [isyangshu/MambaMIL#16]
Why did you use an attention operation to generate the slide features from Mamba's output ?
<img width="346" alt="image" src="https://github.com/isyangshu/MambaMIL/assets/47650134/2a777cfb-0c05-4f67-8bb8-b8022b32d1d4">

I think the traditional Mamba use average pooling to aggregate the sequence.

**Comment by wyhsleep** [comment]
Average pooling is actually a special case of attention aggregation. In our tests, while average pooling can achieve some performance improvement, it is not well-suited to the nature of WSI. Therefore, we used attention for aggregation.

**Comment by anhtienng** [comment]
Ok, I got your idea.
