### ISSUE TITLE
The perplexing experimental results

### ISSUE THREAD

**Issue by dmhdmhdmh** [isyangshu/MambaMIL#22]
In the Cancer Subtyping experiment, the training results using features extracted by PLIP seem even worse than those using features extracted by Resnet50. Moreover, I observed that simply using Max-Pooling appears to outperform most of the comparative methods. I want to ask if you truly conducted your experiments with the necessary rigor and seriousness?
<img width="814" alt="屏幕截图 2024-08-28 233826" src="https://github.com/user-attachments/assets/56b87174-e4f1-4a26-a318-e361d3ff2f13">

**Comment by isyangshu** [comment]
In [1][2][3], for several methods, they achieve similar performance by utilizing the features obtained from ResNet-50 and the features obtained from PLIP.
[1] Feature Re-Embedding: Towards Foundation Model-Level Performance in Computational Pathology
[2] Towards A Generalizable Pathology Foundation Model via Unified Knowledge Distillation
[3] A Multimodal Knowledge-enhanced Whole-slide Pathology Foundation Model

For the ResNet-50, Max-Pooling only outperforms TransMIL in BRACS-7* and BRACS-7, and achieves the lowest performance in the Mean results. In the NSCLS-2, Max-Pooling outperforms most of the comparative methods, and Mamba2MIL (recent work: https://www.arxiv.org/pdf/2408.15032) gets the similar conclusions, where the Max-Pooling gets the third highest performance in the NSCLS dataset. 

I hope that you can directly repeat my experiments by using provided codes before criticizing the rigor and accuracy of my experiments in the paper.
