### ISSUE TITLE
如何传参数获得 512*512 patch (20x)呢？ 

### ISSUE THREAD

**Issue by blz822** [isyangshu/MambaMIL#5]
尊敬的作者，

       您好！请问 CLAM 在 处理 LUAD 数据集时为了获得 512*512 patch (20x)，create_patches_fp.py和extract_features_fp.py的参数应该怎么设置呢？

期待您的回复。
       
       
       
       
python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --seg --patch --stitch 
CUDA_VISIBLE_DEVICES=0 python extract_features_fp.py --data_h5_dir DIR_TO_COORDS --data_slide_dir DATA_DIRECTORY --csv_path CSV_FILE_NAME --feat_dir FEATURES_DIRECTORY --batch_size 512 --slide_ext .svs

**Comment by wyhsleep** [comment]
Please set --patch_size 512 and make sure the h5 file you got contains coordinate for 512*512 patches.

**Comment by blz822** [comment]
我之前一直在使用DSMIL做预处理，通常还需要设置level，在CLAM中有类似的参数 patch_level ，这个参数使用 0 就可以了吗

**Comment by wyhsleep** [comment]
level = 0 for TCGA slides is 40X I think, you can refer to [CLAM](https://github.com/mahmoodlab/CLAM) for more details.

**Comment by sjjadsa** [comment]
你好，请问你的环境是如何装好的？
