### ISSUE TITLE
where is 'Sequence Reordering Operation' in the codebase

### ISSUE THREAD

**Issue by poult-lab** [isyangshu/MambaMIL#7]
Hello, author! I wanted to express my appreciation for your work; I find it truly impressive. In the paper, you introduced the 'Sequence Reordering Operation.' Could you kindly direct me to the specific location within the codebase where this technique is implemented? I'm interested in knowing the exact line and file in the repository. Thank you!

**Comment by wyhsleep** [comment]
It's in `mamba/mamba_ssm/modules/srmamba.py`.

**Comment by poult-lab** [comment]
> It's in `mamba/mamba_ssm/modules/srmamba.py`.

Dear author, I came across line 308 in the file mamba/mamba_ssm/modules/srmamba.py, where it appears that the variable y_f is referenced without prior definition. Could you kindly shed some light on this?

**Comment by isyangshu** [comment]
Sorry, we don't utilize the code between L234-L308. We directly use the code between L201-L232. We will test the L234-L308 in the future.

**Comment by poult-lab** [comment]
Okay, thank you for your prompt response.
