### ISSUE TITLE
Patch Size and Evaluation code

### ISSUE THREAD

**Issue by shubhaminnani** [isyangshu/MambaMIL#9]
This is an amazing repo. I have few questions.
1. Why do we need a patch size of 512, can't we use some other size?
2. Do you intend to release evaluation code and heatmap scripts for the repository?
3. Can we change the feature extractor?

Thanks,
Shubham

**Comment by wyhsleep** [comment]
Thank you for your interest,
1. We can use other sizes like 256 x 256 for each patch.
2. We have released the evaluation code. For current version we couldn't provide heatmap scripts, you can refer to CLAM if you are interested.
3. Of course, in our paper we use two different feature extractors and you can also use other powerful extractors like UNI or CONCH.

**Comment by shubhaminnani** [comment]
For 2, the evaluation is within the training, what if I want to just evaluste on external set and see probabilities just like CLAM has eval.py

**Comment by wyhsleep** [comment]
We will add this eval.py in our next version, you can also make some simple modifications based on our train.py and eval.py in CLAM.

**Comment by shubhaminnani** [comment]
Thank you!
